const furniture = [
    { name: 'Capella Armchair', slug: 'capella-armchair', price: 499, image: 'https://i.imgur.com/jrS1VcT.jpg', description: 'Clad in a sophisticated yet versatile fabric, the Capella armchair stretches out on a modern frame. A padded backrest paired with seats (resilient foam and pocket springs) of medium firmness offers adequate support and lasting comfort. Wing-like armrests nod to timeless elegance. Binge-watch your favourite shows in utmost comfort.' },
    { name: 'Jeanne Armchair', slug: 'jeanne-armchair', price: 429, image: 'https://i.imgur.com/KIuxMTS.jpg', description: 'A subtle nod to mid-century design, the Jeanne armchair mixes elegance with modern comfort. It has a sleek and plush backrest that steals the show, but not the floor space. The sides of the armrests come enveloped by a folding stitch technique which elevates the tailored style of the seat.' },
    { name: 'Jacques Armchair', slug: 'jacques-armchair', price: 639, image: 'https://i.imgur.com/FilgY4m.jpg', description: 'Sink back and relax in this modern classic beauty which fits perfectly in both luxurious and contemporary settings. This is a chair you\'ll love to spend hours in - especially with its deep seat, plush contoured armrests and intricate design details.' },
    { name: 'Mico Armchair', slug: 'mico-armchair', price: 369, image: 'https://i.imgur.com/h5LRZvI.jpg', description: 'Fanning out to embrace your body with comfort, the unique curved form of the Mico armchair offers exceptional support and was developed over many modifications. The rattan weaving and binding has a unique, warm honey tone and a specific clean finish which is not commonly found.' },
    { name: 'Hanford Armchair Leather', price: 1059, slug: 'hanford-armchair-leather', image: 'https://i.imgur.com/Tn88BHj.jpg', description: 'Leather meets livability in the Hanford armchair in soft premium leather. With a deep sprung seat, it\'s all about getting cosy in ultimate comfort. Classic details on the backrest highlight the meticulous craftsmanship of the armchair. Each sofa is unique due to the wide variation of natural tones, grains and markings of leather.' },
    { name: 'Mico Coffee Table', slug: 'mico-coffee-table', price: 399, image: 'https://i.imgur.com/hENUdtJ.jpg', description: 'Bring home relaxed elegance with the open weave design of the Mico coffee table. This modern piece bestows artistic textures to any space. With its circular form, this kid-friendly table emits a light and airy feel to open up your living room. It also features grains of unique variations for a one-of-a-kind piece.' },
  ]

  module.exports = furniture;